### ISSUE TITLE
key not clear where to input

### ISSUE THREAD

**Issue by Iamtheoldman** [calebgeizer/GPT-Docs-Connect#2]
NOT CLEAR ON WHERE TO PLACE KEYS

**Comment by Iamtheoldman** [comment]
KEY function not working in input or in the code

**Comment by calebgeizer** [comment]
Hi,

Make sure you have the document open to attach the extension. After you have pasted code into Apps Script, you need to add the Google Docs API and deploy it as an add-on. You will need to refresh the document you have open. Then a Menu titled 'GPT Connect' will show up. Click that and press settings.
